### ISSUE TITLE
Trakt Rating Dialog displays after playing first file for multipart movie files

### ISSUE THREAD

**Issue by DadeoMP** [Technicolour/Trakt-for-Mediaportal#59]
MediaPortal 1.3.0 alpha. Trakt 2.2.0
Can reproduce with both My Videos and My Films 6.0.1

Movie media files:
The Dark Knight Rises (2012) -CD1.avi
The Dark Knight Rises (2012) -CD2.avi

1. Play the  movie in MP 
2. At end of first file, MP auto plays the second file, but Trakt Rating Dialog pops up and video window is blank/black until you select a rating (or Esc)

**Comment by damienhaynes** [comment]
Im closing this off, if it still occurs in the latest version I will look into it.
