### ISSUE TITLE
Command Line Sync

### ISSUE THREAD

**Issue by MrBobC** [Technicolour/Trakt-for-Mediaportal#96]
It would be great if we could run the library sync from the command line for regularly scheduled syncs.

**Comment by damienhaynes** [comment]
Added the following command line options:
--sync
--silentmode
--closeaftersync (auto enabled with silentmode)

**Comment by MrBobC** [comment]
--closeaftersync does not work.  Silentmode also does not seem to do anything other than open the program from what I can tell.

**Comment by damienhaynes** [comment]
Valid command lines are as follows:
--sync
--sync --silentmode
--sync --closeaftersync

Are you using it like that?
